excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://xenito.github.io
title: xenito
tagline: Sometimes you cannot leave it to other people.
description: A general blog that will focus on improving society by better systems. Well at least that is the intention. 
paginate: 5
